<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.8.9</Version>
		<NoWarn>$(NoWarn);CRYVEEW5001</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW\Cryville.EEW.csproj" Private="false" />
		<ProjectReference Include="..\Cryville.EEW.GeoJSON\Cryville.EEW.GeoJSON.csproj" Private="false" />
		<ProjectReference Include="..\Cryville.EEW.QuakeML\Cryville.EEW.QuakeML.csproj" Private="false" />
	</ItemGroup>

</Project>
