<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.10.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW.TTS\Cryville.EEW.TTS.csproj" Private="false" />
		<ProjectReference Include="..\Cryville.EEW.FANStudio\Cryville.EEW.FANStudio.csproj" Private="false" />
	</ItemGroup>

</Project>
