<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.8.9</Version>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Helpers\QuakeML\QuakeML.csproj" />
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW.TagTypeKeys\Cryville.EEW.TagTypeKeys.csproj" Private="false" />
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW\Cryville.EEW.csproj" Private="false" />
	</ItemGroup>

</Project>
