<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.8.7</Version>
		<NoWarn>$(NoWarn);CRYVEEW5001</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW.TagTypeKeys\Cryville.EEW.TagTypeKeys.csproj" Private="false" />
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW\Cryville.EEW.csproj" Private="false" />
		<ProjectReference Include="..\Cryville.EEW.CENC\Cryville.EEW.CENC.csproj" Private="false" />
		<ProjectReference Include="..\Cryville.EEW.CWA\Cryville.EEW.CWA.csproj" Private="false" />
	</ItemGroup>

</Project>
