<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.8.10</Version>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW.TTS\Cryville.EEW.TTS.csproj" Private="false" />
		<ProjectReference Include="..\Cryville.EEW.CWAOpenData\Cryville.EEW.CWAOpenData.csproj" Private="false" />
	</ItemGroup>

</Project>
