<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.8.2</Version>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW.Features\Cryville.EEW.Features.csproj" Private="false" />
		<ProjectReference Include="..\Cryville.EEW.GeoJSON\Cryville.EEW.GeoJSON.csproj" Private="false" />
	</ItemGroup>

</Project>
