<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Version>0.8.7</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Cryville.Interop.Java.ObjectStream" Version="0.0.5" PrivateAssets="contentfiles;analyzers;build;runtime" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW.TagTypeKeys\Cryville.EEW.TagTypeKeys.csproj" Private="false" />
		<ProjectReference Include="..\..\Interfaces\Cryville.EEW\Cryville.EEW.csproj" Private="false" />
	</ItemGroup>

</Project>
